### PR TITLE
Beta variable fonts

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey,

The engineers at Google Fonts need a few variable fonts to test out some infrastructure. They decided to pick this project.

The sources have been fixed so that variable fonts can be generated using Fontmake.

### CODE REVIEW

**Comment by davelab6** [comment]
LGTM

**Comment by FAlthausen** [comment]
@m4rc1e 
Sorry I am not an GitHub expert:
I changed my local glyphs files manually (with help of “MergeGlyphs”) to include your changes as well as my (local) fixes since my last commit. But now it says “This branch has conflicts”.
Do you like to check the source files again? 
How do I include the varfonts and fontmaker thing now?
Thanks

**Comment by m4rc1e** [comment]
I'll sort this out.

please don't push anything until I do.

**Comment by m4rc1e** [comment]
Alright, I regenned the fonts from the new sources.

**Comment by davelab6** [comment]
Thanks Frederich!

**Pull request merged**
